"""
The one architectural rule of this simulator.

Every cryptographic operation goes through this interface.  The protocol layer
imports `Backend` and nothing else - never py_ecc, never hashlib directly.  That
is what makes the two backends interchangeable and what stops a fast
approximation from quietly leaking into a "faithful" measurement.

Both backends work exclusively inside the subgroup generated by P, because that
is all the protocol ever needs: every G1 element in Tan et al.'s scheme is a
known scalar multiple of the generator.

Operations
----------
g1_mul(k)              k * P
g1_add(A, B)           A + B
g1_sub(A, B)           A - B
pair_with_P(A)         e(A, P)          - a real pairing on a received point
e_PP_pow(k)            e(P, P) ** k     - used where the TA knows both scalars
gt_mul / gt_pow / gt_eq / gt_one        - arithmetic in the target group
"""

from __future__ import annotations

import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any


@dataclass
class OpCount:
    """Counts primitive operations, attributed to whoever performed them.

    This is how the simulator separates TUAV-side cost from TA-side cost - the
    split that the paper never reports.
    """
    g1_mul: int = 0
    g1_add: int = 0
    pairing: int = 0
    gt_mul: int = 0
    gt_pow: int = 0
    hash: int = 0
    wall_ms: float = 0.0

    def copy(self) -> "OpCount":
        return OpCount(self.g1_mul, self.g1_add, self.pairing, self.gt_mul,
                       self.gt_pow, self.hash, self.wall_ms)

    def minus(self, earlier: "OpCount") -> "OpCount":
        """Primitive counts performed since `earlier` was snapshotted."""
        return OpCount(
            g1_mul=self.g1_mul - earlier.g1_mul,
            g1_add=self.g1_add - earlier.g1_add,
            pairing=self.pairing - earlier.pairing,
            gt_mul=self.gt_mul - earlier.gt_mul,
            gt_pow=self.gt_pow - earlier.gt_pow,
            hash=self.hash - earlier.hash,
            wall_ms=0.0,
        )

    def merge(self, other: "OpCount") -> "OpCount":
        return OpCount(
            g1_mul=self.g1_mul + other.g1_mul,
            g1_add=self.g1_add + other.g1_add,
            pairing=self.pairing + other.pairing,
            gt_mul=self.gt_mul + other.gt_mul,
            gt_pow=self.gt_pow + other.gt_pow,
            hash=self.hash + other.hash,
            wall_ms=self.wall_ms + other.wall_ms,
        )

    def as_dict(self) -> dict:
        return {
            "G1 mult": self.g1_mul,
            "G1 add": self.g1_add,
            "pairings": self.pairing,
            "GT mult": self.gt_mul,
            "GT pow": self.gt_pow,
            "hashes": self.hash,
            "wall ms": round(self.wall_ms, 3),
        }


class Timer:
    """Context manager that adds elapsed wall time to an OpCount."""

    def __init__(self, counter: OpCount):
        self.counter = counter

    def __enter__(self):
        self._t0 = time.perf_counter()
        return self

    def __exit__(self, *exc):
        self.counter.wall_ms += (time.perf_counter() - self._t0) * 1000.0
        return False


class Backend(ABC):
    """Protocol-level cryptographic operations."""

    NAME: str = "abstract-base"
    FIDELITY: str = "UNDEFINED"       # "FAITHFUL" | "ABSTRACTED"
    NOTE: str = ""
    SECURITY_NOTE: str = ""

    #: group order q - all scalars live in Z_q
    order: int

    # ---------------------------------------------------------------- G1 ----
    @abstractmethod
    def g1_mul(self, k: int) -> Any:
        """Return k * P."""

    @abstractmethod
    def g1_add(self, a: Any, b: Any) -> Any:
        """Return A + B."""

    @abstractmethod
    def g1_sub(self, a: Any, b: Any) -> Any:
        """Return A - B."""

    @abstractmethod
    def g1_point_mul(self, a: Any, k: int) -> Any:
        """Return k * A for an arbitrary point A.

        Distinct from g1_mul, which multiplies the generator. A UAV computing
        upsilon_i * xi_i * Q_tu holds Q_tu as a *point* received in the Step IS5
        broadcast; it does not know the TUAV's secret and could not rebuild it.
        Keeping these two operations separate is what stops the simulator from
        quietly cheating.
        """

    @abstractmethod
    def g1_repr(self, a: Any) -> str:
        """Short printable form, for the packet inspector in the UI."""

    # ----------------------------------------------------------- pairing ----
    @abstractmethod
    def pair_with_P(self, a: Any) -> Any:
        """Return e(A, P).

        This is a genuine pairing evaluation on a point received from the
        network.  In the faithful backend it is the expensive operation; it is
        the one the TA cannot shortcut, because the whole point is to verify
        bytes that arrived rather than to recompute them.
        """

    @abstractmethod
    def e_PP_pow(self, k: int) -> Any:
        """Return e(P, P) ** k.

        Used for mu_i and delta_i, where the TA constructs BOTH arguments and
        therefore knows both scalars.  Since e(aP, bP) = e(P, P) ** (ab), this
        is mathematically identical to evaluating the pairing and is what any
        real implementation would do.  It is documented rather than hidden.
        """

    # ---------------------------------------------------------------- GT ----
    @abstractmethod
    def gt_mul(self, a: Any, b: Any) -> Any: ...

    @abstractmethod
    def gt_pow(self, a: Any, k: int) -> Any: ...

    @abstractmethod
    def gt_eq(self, a: Any, b: Any) -> bool: ...

    @abstractmethod
    def gt_one(self) -> Any: ...

    # ------------------------------------------------------------ helpers ---
    def gt_prod(self, items) -> Any:
        """Product of a sequence of GT elements."""
        acc = self.gt_one()
        for it in items:
            acc = self.gt_mul(acc, it)
        return acc

    def describe(self) -> dict:
        return {
            "name": self.NAME,
            "fidelity": self.FIDELITY,
            "note": self.NOTE,
            "security": self.SECURITY_NOTE,
            "order_bits": self.order.bit_length(),
        }


def get_backend(name: str) -> Backend:
    """Factory. `name` is 'faithful' or 'abstract'."""
    key = (name or "").strip().lower()
    if key in ("faithful", "pairing", "bn128", "real"):
        from .backend_pairing import PairingBackend
        return PairingBackend()
    if key in ("abstract", "abstracted", "toy", "fast"):
        from .backend_abstract import AbstractBackend
        return AbstractBackend()
    raise ValueError(f"unknown backend {name!r}; use 'faithful' or 'abstract'")
